name: locmate
description: Visual editor for Application Resource Bundle localization files to be used with the intl package.
version: 0.0.2
homepage: https://github.com/msxenon/locmate
repository: https://github.com/msxenon/locmate

environment:
  sdk: ^3.6.1

dependencies: 
  alfred: ^1.1.2+1
  args: ^2.6.0
  path: ^1.9.0
  tint: ^2.0.1
  emojis: ^0.9.9
  yaml: ^3.1.3
  dart_mappable: ^4.4.0
  yaml_edit: ^2.2.2
  web_socket_channel: ^3.0.3

dev_dependencies: 
  lints: ^5.1.1
  test: any
  build_runner: ^2.1.4
  dart_mappable_builder: ^4.2.3